name: uniball_frontend_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  intl: ^0.18.1 #Datum
  google_nav_bar: ^5.0.7
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  http: ^1.3.0
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1
  image_picker: ^1.1.2
  shake: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
  - assets/ #hämtar allt från denna map

#    - assets/uniballLogo.png
#    - assets/goldTrophy.png
